name: Newman API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Newman
      run: npm install -g newman

    - name: Run API tests with Newman
      run: |
        newman run repositorio_postman/postman/cee-collection.json -e repositorio_postman/postman/testes/variaveis.postman_environment.json --reporters cli
